<?php
declare(strict_types=1);

namespace LogLens\Storage\Schema;

/**
 * A fluent, engine-neutral description of one table's columns, indexes, and
 * foreign keys — Log Lens's answer to Laravel's `Blueprint`, scoped to
 * exactly the ~15 primitives this schema actually uses rather than a fully
 * general DDL DSL. A {@see Migration} builds one via {@see Schema::create()}
 * (a new table) or {@see Schema::table()} (adding to an existing one); a
 * {@see Grammar} compiles it to that engine's SQL. The same Blueprint API
 * works for both — creating vs. altering only changes how the Grammar
 * compiles it, never how a migration is written.
 */
final class Blueprint
{
    /** @var list<ColumnDefinition> */
    public array $columns = [];

    /** @var list<IndexDefinition> */
    public array $indexes = [];

    /** @var list<ForeignKeyDefinition> */
    public array $foreignKeys = [];

    /** @var list<string> columns to drop — only meaningful in a down() migration via Schema::table(). */
    public array $dropColumns = [];

    /** @var list<string> index names to drop — only meaningful in a down() migration via Schema::table(). Drop an index before dropping any column it references (the engine rejects dropping a still-indexed column). */
    public array $dropIndexes = [];

    public function __construct(public readonly string $table)
    {
    }

    /** Auto-incrementing integer primary key, named `id` by convention. */
    public function id(): ColumnDefinition
    {
        return $this->addColumn('increments', 'id');
    }

    public function integer(string $name): ColumnDefinition
    {
        return $this->addColumn('integer', $name);
    }

    public function real(string $name): ColumnDefinition
    {
        return $this->addColumn('real', $name);
    }

    /** Unbounded text — the default for free-form content (messages, stacks, context, config JSON, …). */
    public function text(string $name): ColumnDefinition
    {
        return $this->addColumn('text', $name);
    }

    /**
     * Bounded text — TEXT on SQLite/Postgres (unbounded there regardless);
     * a length-bounded VARCHAR on MySQL, which cannot key or default a TEXT
     * column. Use for anything unique, indexed, or carrying a schema-level
     * default; $length only matters to MySQL.
     */
    public function string(string $name, int $length = 191): ColumnDefinition
    {
        $column = $this->addColumn('string', $name);
        $column->length = $length;
        return $column;
    }

    /**
     * A timestamp stored as text, in this app's canonical
     * `'YYYY-MM-DD HH:MM:SS'` UTC string format on every engine (not a native
     * temporal type) — the app does string operations on these
     * (`substr(created_at,1,10)`, lexicographic ORDER BY) that a temporal
     * type would reject. Chain `->useCurrent()` for a default of "now".
     */
    public function timestamp(string $name): ColumnDefinition
    {
        return $this->string($name, 32);
    }

    /**
     * A column generated from `substr(sourceColumn, start, length)` (used
     * for `occurred_day`). Always text.
     */
    public function generatedSubstring(string $name, string $sourceColumn, int $start, int $length): ColumnDefinition
    {
        $column = $this->addColumn('text', $name);
        $column->generated = GeneratedColumn::substring($sourceColumn, $start, $length);
        return $column;
    }

    /**
     * A column generated by extracting `jsonPath` out of a JSON-valued
     * `sourceColumn` — NULL (never an error) when the source isn't valid
     * JSON, since most rows' `context_preview` is free text, not JSON. Used
     * for the four access-log fields parsed out of nginx access rows.
     *
     * $mysqlVarcharLength only matters on MySQL, and only if this column will
     * be indexed (MySQL cannot index a generated TEXT/BLOB column without an
     * explicit bound) — pass it whenever the migration also indexes this
     * column; omit it for one that never is (e.g. `access_agent`).
     */
    public function generatedJson(string $name, string $sourceColumn, string $jsonPath, string $castType = 'text', ?int $mysqlVarcharLength = null): ColumnDefinition
    {
        $column = $this->addColumn($castType === 'integer' ? 'integer' : 'text', $name);
        $column->generated = GeneratedColumn::jsonField($sourceColumn, $jsonPath, $castType, $mysqlVarcharLength);
        return $column;
    }

    /** @param list<string> $columns */
    public function unique(array $columns, string $name): IndexDefinition
    {
        $index = new IndexDefinition('unique', $columns, $name);
        $this->indexes[] = $index;
        return $index;
    }

    /** @param list<string> $columns */
    public function index(array $columns, string $name): IndexDefinition
    {
        $index = new IndexDefinition('index', $columns, $name);
        $this->indexes[] = $index;
        return $index;
    }

    /** @param list<string> $columns */
    public function primary(array $columns): IndexDefinition
    {
        $index = new IndexDefinition('primary', $columns, '');
        $this->indexes[] = $index;
        return $index;
    }

    public function foreign(string $column): ForeignKeyDefinition
    {
        $foreignKey = new ForeignKeyDefinition($column);
        $this->foreignKeys[] = $foreignKey;
        return $foreignKey;
    }

    /** Only meaningful inside a down() migration's Schema::table() callback. */
    public function dropColumn(string $name): void
    {
        $this->dropColumns[] = $name;
    }

    /** Only meaningful inside a down() migration's Schema::table() callback; call before dropColumn() for any column this index references. */
    public function dropIndex(string $name): void
    {
        $this->dropIndexes[] = $name;
    }

    private function addColumn(string $type, string $name): ColumnDefinition
    {
        $column = new ColumnDefinition($name, $type);
        $this->columns[] = $column;
        return $column;
    }
}
